---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections: 
upload_dir: ''
public_path: https://res.cloudinary.com/paulportfolio/image/upload/c_fit.q_auto,f_auto,dpr_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - ELEVENTY_ENV=staging
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run staging
